server:
  port: 29904

spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: secret-key-eatgo-fastcampus-project

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test